[build]
  command = "npm run build"
  publish = "/projects/memoreel/"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[redirects]]
  from = "projects/memoreel/*"
  to = "projects/memoreel/index.html"
  status = 200